### ISSUE TITLE
Direction indicator on map

### ISSUE THREAD

**Issue by TVOps** [nomns/nparse#11]
Currently there is an indicator but what I've tried to do is modify the directional.png icon to show a longer dotted line (mainly for running across zones so I can line it up to beeline directly where I want to go. But the offset is wrong as it wants to be centered. Is this an easy fix? That line is also going _behind me_ instead of ahead.

![map](https://user-images.githubusercontent.com/32497079/47958783-f902a500-dfa8-11e8-9526-cbb2cec562d4.png)

**Comment by nomns** [comment]
I mean.. I don't know whether it's an easy fix as that directional was meant to be centered around the character marker.  I created way points for this exact reason.  Right click on the map, create way point.  Next time you do a /loc, it will show a dotted green line between you and your way point.

**Comment by TVOps** [comment]
Ahh I didn't even think to use the waypoint that way. I haven't used the spawn points and way points since they are not saved after zoning. I'll definitely use the waypoint marker for these beeline maneuvers now though.

**Comment by nomns** [comment]
The spawn points were for tracking spawns as you kill them.  Create spawn point where mob spawns with proper respawn timer, once you kill that mob, click on spawn timer and it will reset the timer.  They weren't made with zoning in mind -- only a temporary tracker if you were camping a certain mob or wanted to keep track of respawns.
