### ISSUE TITLE
Poor Linux support

### ISSUE THREAD

**Issue by Broam** [nomns/nparse#16]
So the program installs fine (sudo apt install python3-pyqt5 required) but setting the EQ log directory to "/home/brian/.wine/drive_c/Program Files (x86)/Sony/EverQuest/Logs" manually in the .json causes the windows to not show.

The system tray "settings" menu is not visible in Ubuntu - right-clicking the N icon only shows me a menu to show windows, not edit settings. Please add another way to change settings via the program.

**Comment by nomns** [comment]
I don't really support Linux, but it should run on Linux.  I have tested before. 

Currently installing Ubuntu on a VirtualBox drive and will test.

**Comment by nomns** [comment]
Works for me.  Menu items are all there.

1. Fresh install of Ubuntu 18.04.3 64 bit
2. sudo apt install git pip3
3. pip3 install pyqt5
4. git clone https://github.com/nomns/nparse.git
5. cd nparse
6. python3 nparse.py

**Comment by nomns** [comment]
![image](https://user-images.githubusercontent.com/932005/69767463-f9d12080-1141-11ea-83dd-0409fdc824a5.png)

**Comment by Broam** [comment]
`sudo apt install python3 python3-pip python3-pyqt5`

The package is python3-pip, not pip3.
I am using the release, not the latest git.

After manually setting the path in the config.json, running python3 nparse.py just hangs.

**Comment by nomns** [comment]
Yes, my apologies.  I put the wrong package for pip3.

Please install pyqt5 via pip and not apt. -> pip3 install pyqt5

This works for me.  The settings menu comes up and I can choose the python directory from there.

**Comment by nomns** [comment]
You can delete the nparse.config.json file if it is not working, as the file is recreated with defaults if nparse doesn't find it.

**Comment by nomns** [comment]
If you do use pyqt5 via pip instead of through apt, you should see warning/error outputs. 

nParse works for me on a fresh install of Ubuntu. I am unsure of what is happening on your system to make this not work, so I am going to close this. There is nothing within the code that requires Windows.  It should work on any system with Python3 and PyQt5 -- Windows/Mac/Linux.

If you do get some error information, please reopen this issue with new information.

**Comment by WaywardWebDesign** [comment]
Hi Nomns, big fan of your program, had it working flawlessly under Windows, and have managed to install under Ubuntu.
Logging enabled, and Nparse pointed to correct folder, however I'm not getting map updates and as soon as I cast a spell it crashes. Any chance you could assist?

[nparse.txt](https://github.com/nomns/nparse/files/11705935/nparse.txt)
