### ISSUE TITLE
No Logs Found

### ISSUE THREAD

**Issue by Haakaah** [nomns/nparse#21]
Hello,
I put the good directory of my P99 Project but i have this message:
No EQ log files were found 
My Eqlog.ini is in the folder but do not work
Any suggestion please?

Regards

**Comment by nomns** [comment]
Did you follow the instructions found here under steps?

https://github.com/nomns/nparse/wiki/Installation

**Comment by Haakaah** [comment]
Sorry Mate is work fine now
good job !

Regards

**Comment by nomns** [comment]
Glad you got it working!

**Comment by Haakaah** [comment]
Just a suggestion:

it was possible writing a big title of zones ?
may be into the next update :)
Realy great job!

Regards

**Comment by nomns** [comment]
What do you mean by writing a big title of zones?

**Comment by Haakaah** [comment]
When we zone on a new map we don't know we are
do you understand?
