### ISSUE TITLE
Reset map zoom

### ISSUE THREAD

**Issue by casperinmd** [nomns/nparse#22]
NOt sure how I did it, but I managed to zoom out so far the whole map is a tiny speck.

ALT + scroll up or down simply kept zooming out. How do I fix that without resetting my settings? 

If i need to delete and download again, I certainly can, but wanted to bring it to your attention.

Thanks!!

**Comment by casperinmd** [comment]
Actually I found the issue. I did reset zoom in the json file, but hten it did it again when scrolling, it was b/c I am doing an ALT + scroll, that will always scroll out regardless of mouse wheel direction.

If you just mouse scroll, it works as intended. doh

**Comment by nomns** [comment]
ahh :) I didn't realize alt messed with mouse scroll like that!  Glad you got it sorted.
