### ISSUE TITLE
Spells no more work with second my second caracater

### ISSUE THREAD

**Issue by Haakaah** [nomns/nparse#25]
When i was switch to my seconde caracter map continue working good but no more spells
i have deleted my logs files and option file on Nparse and reinstall all but not working

**Comment by nomns** [comment]
So only 1 of your characters' spells isn't working?  Your other character has spells working?
Both characters have maps working?

**Comment by Haakaah** [comment]
Map work on both caracters but spell do not work on both too

**Comment by nomns** [comment]
What spell are you trying to cast that doesn't work?

**Comment by Haakaah** [comment]
i have a wiz lvl 10 & shaman lvl 18 all spells do not work
until i switch caracter all shaman spell working fine

**Comment by nomns** [comment]
Both these characters are on Project 1999?

So, your level 10 wizard spells aren't working?  Casting lesser shielding on yourself doesn't work?

**Comment by Haakaah** [comment]
all caracter are on P99
lesser shielding don't work

**Comment by nomns** [comment]
So it's just your level wizard spells that aren't working?

**Comment by Haakaah** [comment]
all spell don't work on wizard
and all spell don't work on shaman now

**Comment by nomns** [comment]
Can you see the spell window?  Have you set the level of the characters on the spell window?

**Comment by Haakaah** [comment]
i see the spell window but nothing on this window the same at lvl 1 or lvl 10
same with shaman : i see the spell wiindow but nothing on it lvl 1 or lvl 18

**Comment by nomns** [comment]
Try turning the spell window off.  It's in settings under spells.

If you have a bad connection or your computer is slower, the spell window may not work.

**Comment by Haakaah** [comment]
i try all i can do
my pc is a good pc & connexion too

**Comment by nomns** [comment]
So you turned off the casting window and then tried?

**Comment by Haakaah** [comment]
yep i try all the solution is on your camp

**Comment by nomns** [comment]
Can you show me parts of your logs that have your character casting a spell and the spell landing?

Also, if you have an antivirus, you may want to try white flagging the nParse folder.

**Comment by Haakaah** [comment]
[eqlog_Ombreduval_project1999.txt](https://github.com/nomns/nparse/files/4714059/eqlog_Ombreduval_project1999.txt)

**Comment by nomns** [comment]
None of your casts have landing lines. No wonder nothing is parsing.  Have you filtered what prints in Everquest?

You casting root:
`
[Tue Jun 02 02:04:41 2020] You begin casting Root.
[Tue Jun 02 02:04:41 2020] An asp bashes YOU for 8 points of damage.
[Tue Jun 02 02:04:41 2020] An asp tries to bite YOU, but misses!
[Tue Jun 02 02:04:43 2020] You regain your concentration and continue your casting.
[Tue Jun 02 02:04:52 2020] You begin casting Fire Bolt.
`

Me casting root:
`
[Fri May 29 20:19:07 2020] You begin casting Root.
[Fri May 29 20:19:09 2020] A forest giant arbor tries to hit YOU, but misses!
[Fri May 29 20:19:09 2020] A forest giant arbor hits YOU for 14 points of damage.
[Fri May 29 20:19:09 2020] You regain your concentration and continue your casting.
[Fri May 29 20:19:09 2020] **A forest giant arbor's feet adhere to the ground.**
`

**Comment by Haakaah** [comment]
so ?

**Comment by nomns** [comment]
Your log file does not contain all the lines it needs.
You are missing lines when the spell lands on the target.  That is what I parse for a complete spell cast. 

When you root something, it should then say "target's feet adhere to the ground."  When YOU cast root, that line does not show in your log.  I think you have filtered out things in your Everquest client.

This is not an issue with my program.  This is an issue with your Everquest.

**Comment by Haakaah** [comment]
all melee & spell dommage are filtered now but same problem

**Comment by nomns** [comment]
Note: **PC Spells** under Options -> Filters when set to Hide stop landing messages from showing up in logs.
