### ISSUE TITLE
Shaman Epic - Custom Spell Timer

### ISSUE THREAD

**Issue by Bogron** [nomns/nparse#29]
Tried using a custom spell timer trigger for the shaman epic, it doesn't seem to be working?

![SpearFate](https://user-images.githubusercontent.com/68516590/87884197-6ab29a80-c9a8-11ea-8fc7-745a4f4eb36f.jpg)

**Comment by nomns** [comment]
Interesting.  Have you verified that the text shows up in your log file?  There is some filtering you can do within the client that will disable some messages from hitting the log.
