### ISSUE TITLE
Charm Spells

### ISSUE THREAD

**Issue by ObservantRhino** [nomns/nparse#3]
I noticed Charm spell timers still persist for the full duration even if charm breaks or the mob dies.  Not a huge deal, but something that might be tweakable : )

**Comment by nomns** [comment]
I can write this down to look into for charm breaking, but I cannot figure out of your charmed mob is the one who dies unless it also comes with a charm break message.  If you are fighting two 'a skeletons,' and one is your charm and you kill the other.  I have no way to tell the difference.

**Comment by ObservantRhino** [comment]
Understood, I thought it did give a message if it dies as well, but I could be remembering wrong.  I did also notice similar interactions with root spells that break early on a mob and on death that are probably in the same boat.  If there isn't a way around it that's cool.  Great work so far!! :)

**Comment by nomns** [comment]
Since I can't track targets, I am going to close this.  Unfortunately, charm will just be one of those things like root that will show full duration but I won't be able to auto remove without potentially removing a timer you need.
