### ISSUE TITLE
nParse for XP?

### ISSUE THREAD

**Issue by USMCbudder** [nomns/nparse#34]
Hello again, I'm trying to get nParse to run on windows xp AMD 64x2. I've found a few versions of Python that are said to work for xp (3.4.4, 3.4.10 and 2.7.9)but keep getting errors. Any help or guidance would be great! One of the errors was incorrect pathway and the other was something like win32 kernell ddl not found or something.
Thank you,
Ron

**Comment by nomns** [comment]
I am not going to support out of date OS.  Sorry my friend.
