### ISSUE TITLE
Mac OSX compatibility

### ISSUE THREAD

**Issue by maqij** [nomns/nparse#4]
Hello, this project looks really great. I am one of those folks who is using a Mac to play EQ. I run Titanium though Wine and it works fine. However, none of the parsers work with Wine. 

I thought perhaps I could run the python script using MacPython, but I haven't been successful. I also attempted to run the complied exe with Wine, but is not possible either. Is it possible to adapt the script to work in the OSX environment? If so, you would make me and all the other Mac users very happy.

Thanks.

**Comment by nomns** [comment]
If you can run python 3+ (i may have put in some python 3.6 so you may need python 3.6 +) with pyqt5 and PyYaml, it should work (do you have those packages installed with pip)? if you run from a terminal, what error messages are shown?  I'll need more information.

Please be aware that I do not own a any apple products to test this, but I can try to run on a linux box to see if I can get it working there this weekend.

**Comment by maqij** [comment]
You are correct. I just got it working. 

The first problem was that 2.7 was still running the script even though I installed the python 3.6 framework. Once I got 3.6 to run, I had to install the two packages you mentioned (pyqt5 and PyYaml) and a Mac OSX package was suggested and automatically installed after I approved. 

It is wonderful! I am excited to try it out tonight. Thank you so much.

**Comment by nomns** [comment]
Nice!  Let me know if you have any problems going forward using Mac (with my Program, not receiving Unicode).
