### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kupoback** [nomns/nparse#6]
Great work, a simple request is an always on top option if possible

**Comment by nomns** [comment]
You want to turn it off?  Is it not working for you?

Are you running source/exe? What OS?

**Comment by kupoback** [comment]
No, when I am running it on Windows 10, using WinEQ, it is treated as a normal window, where-in if an application that takes up more real estate or is windowed full screen (like a browser), the application hides behind it.

I could not find the option to make it always on top. I followed your wiki after downloading it last night, the latest source version.

**Comment by nomns** [comment]
There is no option to have it always on top.  It's on top by default (it is on my windows box).  The screenshots I have uploaded show it on top while I am playing windows mode.  I don't think I can make it go over a full screen mode game. 

If you click the ☷ twice, does it fix itself?

**Comment by kupoback** [comment]
Oh, I am not asking for it to go full screen, i'm saying that when I use it, either double clicking the icon you mentioned twice, or otherwise, it is not always on top.

**Comment by nomns** [comment]
Do other on top applications work for you?

**Comment by kupoback** [comment]
Yes, I was using another map tool from the forums, but stopped as I didn't like the layout of it. Yours is much more ascetically pleasing. However that programs always on top worked.

**Comment by nomns** [comment]
This is probably a Qt issue.  I'll take a look into this, but this is weird behavior I think.  It sounds like we both use the same OS: mine works and yours doesn't (no one else has said anything either way, so I was thinking it was working).  

My exe isn't digitally signed.  I am hoping its not a security thing with Windows for the binary .  I will add an on top icon in the next couple releases so you can specifically target that window flag and Ill put every thing I can find in that to try and force the behavior.

**Comment by kupoback** [comment]
Thank you, if you want I am very happy to be a tester for you. Like I said, I really like the application methods you have here and they look fantastic with the map styles being from EQ instead of EQAtlas.

You've done a great job!

**Comment by nomns** [comment]
Thanks dude!  This feature (stay on top) is one of the most important things to me about my program.  If it doesn't work, why bother using it?  I wouldn't.  I got two monitors, but then where am I going to play media? :) 

That other program I think is done using C# which plays with windows much nicer than Qt.  I like cross-platform solutions and I guess these types of things are the cost.

I won't have a new release out this weekend, but I am hoping to get this in the next release. (fingers crossed next weekend or before).

I'll close this as soon as the new release is out with some alternate enforcement for on topness.

**Comment by kupoback** [comment]
Sounds fantastic, keep up the good work, I'll be monitoring it and inform you of any issues! As a php developer learning python, I love looking at your source code and seeing what you're doing!

**Comment by nomns** [comment]
Oh sweet, you got python 3+ installed?  
`
pip install pyqt5
pip install pyyaml
git clone https://github.com/nomns/nparse.git 
cd nparse
python nparse.py
`

Does on top work if you run it from source?

**Comment by kupoback** [comment]
I have left my house for work, but I will run this tonight when I get home and see if it works running in python

**Comment by kupoback** [comment]
@nomns Running the script above, the map and spells are on top of my window!

![Desktop Screenshot](https://i.imgur.com/kXxvQvq.png)

**Comment by nomns** [comment]
![download](https://user-images.githubusercontent.com/932005/36623784-7ad5a940-18cd-11e8-9b15-78fd554b8333.jpg)

This may be a windows security issue because I don't digitally sign my exe.  I'll try to look into this before my next release.  

Also, I think I'll start keeping my current git repository the release and create a development branch work on.

Glad it's working for you!

**Comment by kupoback** [comment]
Yeahhh no idea, but i think i will execute via script. it worked great, but will  be on the lookout for the next release.

**Comment by nomns** [comment]
Did you ever try running the exe as administrator?

**Comment by kupoback** [comment]
Yes, and to no avail.

**Comment by nomns** [comment]
Damn, that would have been too easy. hah.  Ok, I'm gonna go ahead and close this out.  I am very happy its up and working for you!  I'll try keep the master git runnable (if its ever broken you can get the source from the release page.).  Let's see if anyone else complains!

**Comment by nomns** [comment]
! Also, since you are a web dev, you can always customize the spell window with the css in data/ui/_.css

Most of the spell window is done with css.   The gradients are a weird qt css thing.

**Comment by kupoback** [comment]
Oh neat! I'll deft play around with it!

**Comment by kupoback** [comment]
@nomns Just wanted to pop in.  Last night, I had WinEQ up and open. Was in LS running to Sol B. Found out I'd be pulling, so I typed in the script to get the application going. It would not sit on top of the window.

**Comment by kupoback** [comment]
Weird, even if i start the script before WinEQ it still does not stay on top.

**Comment by nomns** [comment]
But it worked the other day?

**Comment by nomns** [comment]
Im looking into this right now.  It's super weird for me. like.. I can get them to work, but if I open the application then switch focus to something else, the windows don't go on top.  If I run the application and then don't touch anything, there is a better chance they will stay on top.  This is.. weird behavior.

**Comment by kupoback** [comment]
So you are able to replicate this? It's not just me being crazy?

**Comment by nomns** [comment]
No.. no... you aren't crazy.   It was my fault (i'm the crazy one) -- my parser was using a different framework previously, so all these little things that worked before are done a little differently in Qt.  I just fixed some stuff on my end.  Apparently if an item wasn't toggled on with geometry set, the on top flag wasn't being set.  I've now (a) force set on top regardless whether the window is showing at start (b) coupled the 'on top' toggle with clicking on the 'move' icon for the parsing windows, so (a) will force it to start and (b) will allow you to force toggle it on and off.

I am currently getting new maps together so I can do a release, but as soon as I get those updated, Ill update the master git so you can get the new script.  The executable release should be out mid week.

**Comment by kupoback** [comment]
Ahhh, that makes sense. Well, I'm glad you were quickly able to find the issue and resolve it!

I look forward to updating my local copy!

**Comment by nomns** [comment]
Hey do another clone and check it out -- master git is updated to v0.4 pre release.

I am still having problems but I hope you can get this working. 

If I start the program then don't move your mouse or do anything until it loads, it should load windows properly.  If you start the program then click on another window or alt tab before the program fully loads, the map window doesn't show but the spells window does.  

As I said, the "on top" will now be toggle-able when you click on the ☷ on the parser window.  When the window frame is showing it won't stay on top, when the window frame is not showing, it should stay on top.  

Let me know if this works for you.

**Comment by nomns** [comment]
Ok, give it a shot now.   Let me know!

**Comment by kupoback** [comment]
Seemed to work when i re-cloned it
