### ISSUE TITLE
link overlay "always on top" to EQ window active

### ISSUE THREAD

**Issue by IronMongrel** [nomns/nparse#67]
It would be nice if there were an option to make it so the overlay is only in the foreground if the EverQuest process is in focus. I multitask while playing EverQuest and the overlay is intrusive, I end up simply closing and reopening the program often. I imagine not everybody wants/requires this, so a toggle for this feature seems sensible.

**Comment by rm-you** [comment]
I run into this often too, and that's a really interesting idea. It could definitely be possible. I'll look into it when I have some time!
