### ISSUE TITLE
Crashes on special characters in the log file

### ISSUE THREAD

**Issue by dg891** [nomns/nparse#8]
Special characters in the log file like "《" or "》" cause the program to crash.

**Comment by nomns** [comment]
I was able to use the program both in source form and executable form while spamming 《 or 》and was not able to crash it.

Can you give me more details?  I am currently logged on under 'Mirox' if you want to talk to me there.

**Comment by dg891** [comment]
The specific line I am having that is crashing it is:

[Wed Aug 22 19:04:23 2018] Mignonette says, ' 《 pst  》 c2／gob／e／vog／sos／etc~'

Every time Mignonette fires off her macro, nparse crashes immediately.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dg891** [comment]
[Wed Aug 22 19:04:23 2018] Mignonette says, ' 《 pst  》 c2／gob／e／vog／sos／etc~'

This is the specific line causing the crash.  It is happening on the 0.4 version, running from executable.  WIndows 10 64-bit.

The crash occurs every time that line is executed.

**Comment by nomns** [comment]
Great! Thanks for the updated info.  I was able to reproduce the crash (UnicodeDecodeError).

I'll make a fix and push a new release tonight!

**Comment by nomns** [comment]
Newly released v0.4.1 should fix these problems.  Please let me know if you have any problems.
