### ISSUE TITLE
Feature Request: show Charm timer

### ISSUE THREAD

**Issue by bndlfm** [nomns/nparse#9]
It would be amazing if you could show the charm timer on charmed mobs as a buff/debuff. I know it often breaks early but it's a handy metric to have.

**Comment by nomns** [comment]
I will look into this.  I thought charm spells that had a cast+landing message were working as per #3 issue.

Which charm spell are you using that isn't working?

**Comment by bndlfm** [comment]
I apologize for taking so long to get back to you, I don't think that the
regular "charm" spell has a landing message, but it has a message when it
breaks. I will get you some logs today!

thanks, bndlfm

**Comment by nomns** [comment]
If a spell doesn't have a casting or landing message, my program will not parse it.  I just moved, and finally started playing P99 again, so I should finally have time to create the custom triggers which should answer a lot of these types of questions -- clickies, etc.
